# Generated by Django 4.2.8 on 2024-01-25 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("blog", "0002_postform_body_alter_postform_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="blog_Detail",
            fields=[
                (
                    "postform_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blog.postform",
                    ),
                ),
                ("description", models.TextField()),
            ],
            bases=("blog.postform",),
        ),
    ]
