# Generated by Django 4.2.8 on 2024-02-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploadModel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="upform",
            name="title",
            field=models.CharField(default="general", max_length=255),
        ),
    ]
