# Generated by Django 4.2.8 on 2024-01-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postform",
            name="body",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="postform",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
