# Generated by Django 4.2.8 on 2024-02-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_postform_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="postform",
            name="image",
            field=models.ImageField(default="general", upload_to=""),
        ),
    ]
